security:
  encoders:
    Corohelp\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: Corohelp\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      guard:
        authenticators:
          - Corohelp\Security\LoginFormAuthenticator
      logout:
        path: logout
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 604800 # 1 week in seconds
        path:     /
        secure: true

  access_control:
    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(login|logout|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(seeker|helper)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(seeker|helper), roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/(profile)$, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/category, roles: ROLE_ADMIN }
    - { path: ^/, roles: ROLE_ADMIN }
