index:
  path: /
  controller: \Corohelp\Controller\DefaultController::index

register:
  path: /register
  controller: \Corohelp\Controller\AuthenticationController::register
login:
  path: /login
  controller: \Corohelp\Controller\AuthenticationController::login
logout:
  path: /logout
  controller: \Corohelp\Controller\AuthenticationController::logout

web_profiler_wdt:
  resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
  prefix: /_wdt

web_profiler_profiler:
  resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
  prefix: /_profiler
