index:
  path: /
  controller: \Corohelp\Controller\DefaultController::index

register:
  path: /register
  controller: \Corohelp\Controller\RegistrationController::register

web_profiler_wdt:
  resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
  prefix: /_wdt

web_profiler_profiler:
  resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
  prefix: /_profiler
