index:
  path: /
  controller: \Places\Controller\MainController::index

register:
  path: /register
  controller: \Places\Controller\AuthenticationController::register
login:
  path: /login
  controller: \Places\Controller\AuthenticationController::login
logout:
  path: /logout
  controller: \Places\Controller\AuthenticationController::logout
password_reset:
  path: /reset
  controller: \Places\Controller\AuthenticationController::reset
profile:
  path: /profile
  controller: \Places\Controller\UserController::profile

user_index:
  path: /users
  controller: \Places\Controller\UserController::index
user_new:
  path: /user/new
  controller: \Places\Controller\UserController::new
user_show:
  path: /user/{id}
  controller: \Places\Controller\UserController::show
  methods: GET
  requirements:
    id: '\d+'
user_edit:
  path: /user/{id}/edit
  controller: \Places\Controller\UserController::edit
  requirements:
    id: '\d+'
user_delete:
  path: /user/{id}
  controller: \Places\Controller\UserController::delete
  methods: DELETE
  requirements:
    id: '\d+'
user_resend_confirmation:
  path: /profile/resendconfirmation
  controller: \Places\Controller\UserController::resendConfirmation

category_index:
  path: /category
  controller: \Places\Controller\CategoryController::index
category_new:
  path: /category/new
  controller: \Places\Controller\CategoryController::new
category_show:
  path: /category/{id}
  controller: \Places\Controller\CategoryController::show
  methods: GET
  requirements:
    id: '\d+'
category_edit:
  path: /category/{id}/edit
  controller: \Places\Controller\CategoryController::edit
  requirements:
    id: '\d+'
category_delete:
  path: /category/{id}
  controller: \Places\Controller\CategoryController::delete
  methods: DELETE
  requirements:
    id: '\d+'
place_index:
  path: /place
  controller: \Places\Controller\PlaceController::index
place_new:
  path: /place/new
  controller: \Places\Controller\PlaceController::new
place_show:
  path: /place/{id}
  controller: \Places\Controller\PlaceController::show
  methods: GET
  requirements:
    id: '\d+'
place_edit:
  path: /place/{id}/edit
  controller: \Places\Controller\PlaceController::edit
  requirements:
    id: '\d+'
place_delete:
  path: /place/{id}
  controller: \Places\Controller\PlaceController::delete
  methods: DELETE
  requirements:
    id: '\d+'

email_confirmation:
  path: /confirm/{token}
  controller: \Places\Controller\AuthenticationController::confirm
  requirements:
    token: '.+'